In [3]:
class car:
  def __init__(self,brand,mileage,colour)
    self.brand=brand
    self.mileage=mileage
    self.colour=colour

    def get_info(self):
      return f"I have a car of brand{self.brand},colour{self.colour},mileage{self.mileage}"

    carl =car("toyata",50000,"red")
    print(carl.get_info())


SyntaxError: expected ':' (3198758143.py, line 2)

In [5]:
from abc import ABC, abstractmethod
# Abstract Class
class Car(ABC):
    def __init__(self, color, mileage):
        # Encapsulation
        self.__color = color
        self.__mileage = mileage
    # Getter methods
    def get_color(self):
        return self.__color
    def get_mileage(self):
        return self.__mileage
    # Abstract method (Polymorphism)
    @abstractmethod
    def get_info(self):
        pass
# Inheritance
class Tesla(Car):
    # Polymorphism - own implementation
    def get_info(self):
        return f"Tesla Car of Color: {self.get_color()}, Mileage: {self.get_mileage()} km"
class BMW(Car):
    # Polymorphism - own implementation
    def get_info(self):
        return f"BMW Car of Color: {self.get_color()}, Mileage: {self.get_mileage()} km"
class Audi(Car):
    # Polymorphism - own implementation
    def get_info(self):
        return f"Audi Car of Color: {self.get_color()}, Mileage: {self.get_mileage()} km"
# Objects
car1 = Tesla("Red", 500)
car2 = BMW("Black", 400)
car3 = Audi("White", 450)

# Polymorphism - same method name, different implementations
cars = [car1, car2, car3]
for car in cars:
    print(car.get_info())

Tesla Car of Color: Red, Mileage: 500 km
BMW Car of Color: Black, Mileage: 400 km
Audi Car of Color: White, Mileage: 450 km


In [17]:
my_list =["dog",2,98]
print(list[2])
my_tuple=tuple(my_list)
print(my_tuple)
print(type(my_tuple))

98


TypeError: 'list' object is not callable

In [6]:
L=[20,2,8]
L1=[1,10,12,5,3]
L3=[5,20,4,8,30]
L2=[L1,L,L3]
print(L2)

[[1, 10, 12, 5, 3], [20, 2, 8], [5, 20, 4, 8, 30]]


In [7]:
N=[1:6]
N=[1:6:2]
N[:6]
N[1:]
print(N)

SyntaxError: invalid syntax (2548998309.py, line 1)

In [8]:
import numpy as np

# Creating a 2D array
s = [[1, 2, 3],
     [3, 4, 5],
     [5, 6, 7]]

S1 = np.array(s)

print("Original Array:")
print(S1)

# Indexing
print("\nFirst Row:")
print(S1[0])

print("\nSecond Row:")
print(S1[1])

print("\nLast Row:")
print(S1[-1])

# Accessing elements
print("\nElement at row 0 column 0:")
print(S1[0][0])

print("\nElement at row 1 column 2:")
print(S1[1][2])

# Updating value
S1[0][0] = 12

print("\nUpdated Array:")
print(S1)

# Array addition
S2 = S1 + S1

print("\nAddition of Arrays:")
print(S2)

# 1D array
v = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

print("\n1D Array:")
print(v)

# Adding number
print("\nAdd 5:")
print(v + 5)

print("\nAdd 2:")
print(v + 2)

# Slicing
print("\nFirst 5 elements:")
print(v[:5])

# Reverse array
print("\nReverse Array:")
print(v[::-1])

Original Array:
[[1 2 3]
 [3 4 5]
 [5 6 7]]

First Row:
[1 2 3]

Second Row:
[3 4 5]

Last Row:
[5 6 7]

Element at row 0 column 0:
1

Element at row 1 column 2:
5

Updated Array:
[[12  2  3]
 [ 3  4  5]
 [ 5  6  7]]

Addition of Arrays:
[[24  4  6]
 [ 6  8 10]
 [10 12 14]]

1D Array:
[ 1  2  3  4  5  6  7  8  9 10]

Add 5:
[ 6  7  8  9 10 11 12 13 14 15]

Add 2:
[ 3  4  5  6  7  8  9 10 11 12]

First 5 elements:
[1 2 3 4 5]

Reverse Array:
[10  9  8  7  6  5  4  3  2  1]
